import ScriptEnv
ScriptEnv.Initialize("Ansoft.ElectronicsDesktop")
oDesktop.RestoreWindow()
oProject = oDesktop.SetActiveProject("Materiatronics_modules")
oDesign = oProject.SetActiveDesign("HFSSDesign1")
oEditor = oDesign.SetActiveEditor("3D Modeler")
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Electric_dipole_1:Scale:1"],["NAME:ChangedProps",["NAME:Scale of X","Value:=", "1"],["NAME:Scale of Y","Value:=", "1"],["NAME:Scale of Z","Value:=", "1"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Electric_dipole_1:Rotate:1"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Electric_dipole_1:Rotate:2"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Electric_dipole_2:Scale:1"],["NAME:ChangedProps",["NAME:Scale of X","Value:=", "1"],["NAME:Scale of Y","Value:=", "1"],["NAME:Scale of Z","Value:=", "1"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Electric_dipole_2:Rotate:1"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Electric_dipole_2:Rotate:2"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Electric_dipole_3:Scale:1"],["NAME:ChangedProps",["NAME:Scale of X","Value:=", "1"],["NAME:Scale of Y","Value:=", "1"],["NAME:Scale of Z","Value:=", "1"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Electric_dipole_3:Rotate:1"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Electric_dipole_3:Rotate:2"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Electric_dipole_4:Scale:1"],["NAME:ChangedProps",["NAME:Scale of X","Value:=", "1"],["NAME:Scale of Y","Value:=", "1"],["NAME:Scale of Z","Value:=", "1"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Electric_dipole_4:Rotate:1"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Electric_dipole_4:Rotate:2"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Electric_dipole_5:Scale:1"],["NAME:ChangedProps",["NAME:Scale of X","Value:=", "1"],["NAME:Scale of Y","Value:=", "1"],["NAME:Scale of Z","Value:=", "1"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Electric_dipole_5:Rotate:1"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Electric_dipole_5:Rotate:2"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Electric_dipole_6:Scale:1"],["NAME:ChangedProps",["NAME:Scale of X","Value:=", "1"],["NAME:Scale of Y","Value:=", "1"],["NAME:Scale of Z","Value:=", "1"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Electric_dipole_6:Rotate:1"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Electric_dipole_6:Rotate:2"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Precessing_electric_dipole_real:Scale:2"],["NAME:ChangedProps",["NAME:Scale of X","Value:=", "1"],["NAME:Scale of Y","Value:=", "1"],["NAME:Scale of Z","Value:=", "1"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Precessing_electric_dipole_real:Rotate:1"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Precessing_electric_dipole_real:Rotate:2"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Precessing_electric_dipole_imaginary:Scale:2"],["NAME:ChangedProps",["NAME:Scale of X","Value:=", "1"],["NAME:Scale of Y","Value:=", "1"],["NAME:Scale of Z","Value:=", "1"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Precessing_electric_dipole_imaginary:Rotate:1"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Precessing_electric_dipole_imaginary:Rotate:2"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Cylinder4:Scale:1"],["NAME:ChangedProps",["NAME:Scale of X","Value:=", "1"],["NAME:Scale of Y","Value:=", "1"],["NAME:Scale of Z","Value:=", "1"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Cylinder4:Rotate:1"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Cylinder4:Rotate:2"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Cylinder6:Scale:1"],["NAME:ChangedProps",["NAME:Scale of X","Value:=", "1"],["NAME:Scale of Y","Value:=", "1"],["NAME:Scale of Z","Value:=", "1"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Cylinder6:Rotate:1"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Cylinder6:Rotate:2"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Cylinder8:Scale:1"],["NAME:ChangedProps",["NAME:Scale of X","Value:=", "1"],["NAME:Scale of Y","Value:=", "1"],["NAME:Scale of Z","Value:=", "1"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Cylinder8:Rotate:1"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Cylinder8:Rotate:2"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Cylinder10:Scale:1"],["NAME:ChangedProps",["NAME:Scale of X","Value:=", "1"],["NAME:Scale of Y","Value:=", "1"],["NAME:Scale of Z","Value:=", "1"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Cylinder10:Rotate:1"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Cylinder10:Rotate:2"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Cylinder12:Scale:1"],["NAME:ChangedProps",["NAME:Scale of X","Value:=", "1"],["NAME:Scale of Y","Value:=", "1"],["NAME:Scale of Z","Value:=", "1"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Cylinder12:Rotate:1"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Cylinder12:Rotate:2"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Cylinder14:Scale:1"],["NAME:ChangedProps",["NAME:Scale of X","Value:=", "1"],["NAME:Scale of Y","Value:=", "1"],["NAME:Scale of Z","Value:=", "1"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Cylinder14:Rotate:1"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Cylinder14:Rotate:2"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Precessing_magnetic_dipole_real:Scale:2"],["NAME:ChangedProps",["NAME:Scale of X","Value:=", "1"],["NAME:Scale of Y","Value:=", "1"],["NAME:Scale of Z","Value:=", "1"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Precessing_magnetic_dipole_real:Rotate:1"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Precessing_magnetic_dipole_real:Rotate:2"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Precessing_magnetic_dipole_imaginary:Scale:2"],["NAME:ChangedProps",["NAME:Scale of X","Value:=", "1"],["NAME:Scale of Y","Value:=", "1"],["NAME:Scale of Z","Value:=", "1"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Precessing_magnetic_dipole_imaginary:Rotate:1"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Precessing_magnetic_dipole_imaginary:Rotate:2"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","EquationCurve1:Scale:1"],["NAME:ChangedProps",["NAME:Scale of X","Value:=", "1"],["NAME:Scale of Y","Value:=", "1"],["NAME:Scale of Z","Value:=", "1"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","EquationCurve1:Rotate:1"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","EquationCurve1:Rotate:2"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","EquationCurve1:CreateEquationCurve:1"],["NAME:ChangedProps",["NAME:Y(_t)","Value:=","1*lambda/25*sin(_t)"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","EquationCurve2:Scale:1"],["NAME:ChangedProps",["NAME:Scale of X","Value:=", "1"],["NAME:Scale of Y","Value:=", "1"],["NAME:Scale of Z","Value:=", "1"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","EquationCurve2:Rotate:1"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","EquationCurve2:Rotate:2"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","EquationCurve2:CreateEquationCurve:1"],["NAME:ChangedProps",["NAME:Y(_t)","Value:=","1*lambda/25*sin(_t)"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","EquationCurve3:Scale:1"],["NAME:ChangedProps",["NAME:Scale of X","Value:=", "1"],["NAME:Scale of Y","Value:=", "1"],["NAME:Scale of Z","Value:=", "1"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","EquationCurve3:Rotate:1"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","EquationCurve3:Rotate:2"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","EquationCurve3:CreateEquationCurve:1"],["NAME:ChangedProps",["NAME:Y(_t)","Value:=","1*lambda/25*sin(_t)"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","EquationCurve4:Scale:1"],["NAME:ChangedProps",["NAME:Scale of X","Value:=", "1"],["NAME:Scale of Y","Value:=", "1"],["NAME:Scale of Z","Value:=", "1"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","EquationCurve4:Rotate:1"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","EquationCurve4:Rotate:2"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","EquationCurve4:CreateEquationCurve:1"],["NAME:ChangedProps",["NAME:Y(_t)","Value:=","1*lambda/25*sin(_t)"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","EquationCurve5:Scale:1"],["NAME:ChangedProps",["NAME:Scale of X","Value:=", "1"],["NAME:Scale of Y","Value:=", "1"],["NAME:Scale of Z","Value:=", "1"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","EquationCurve5:Rotate:1"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","EquationCurve5:Rotate:2"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","EquationCurve5:CreateEquationCurve:1"],["NAME:ChangedProps",["NAME:Y(_t)","Value:=","1*lambda/25*sin(_t)"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","EquationCurve6:Scale:1"],["NAME:ChangedProps",["NAME:Scale of X","Value:=", "1"],["NAME:Scale of Y","Value:=", "1"],["NAME:Scale of Z","Value:=", "1"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","EquationCurve6:Rotate:1"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","EquationCurve6:Rotate:2"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","EquationCurve6:CreateEquationCurve:1"],["NAME:ChangedProps",["NAME:Y(_t)","Value:=","1*lambda/25*sin(_t)"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Cylinder24:Scale:1"],["NAME:ChangedProps",["NAME:Scale of X","Value:=", "1"],["NAME:Scale of Y","Value:=", "1"],["NAME:Scale of Z","Value:=", "1"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Cylinder24:Rotate:3"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Cylinder24:Rotate:4"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Cylinder26:Scale:1"],["NAME:ChangedProps",["NAME:Scale of X","Value:=", "1"],["NAME:Scale of Y","Value:=", "1"],["NAME:Scale of Z","Value:=", "1"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Cylinder26:Rotate:3"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Cylinder26:Rotate:4"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","striptel1:Scale:1"],["NAME:ChangedProps",["NAME:Scale of X","Value:=", "1"],["NAME:Scale of Y","Value:=", "1"],["NAME:Scale of Z","Value:=", "1"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","striptel1:Rotate:1"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","striptel1:Rotate:2"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","striptel1:CreateCylinder:1"],["NAME:ChangedProps",["NAME:Center Position","X:=","0","Y:=","1*lambda/25","Z:=", "-lambda/5/2"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","striptel2:Scale:1"],["NAME:ChangedProps",["NAME:Scale of X","Value:=", "1"],["NAME:Scale of Y","Value:=", "1"],["NAME:Scale of Z","Value:=", "1"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","striptel2:Rotate:1"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","striptel2:Rotate:2"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","striptel2:CreateCylinder:1"],["NAME:ChangedProps",["NAME:Center Position","X:=","0","Y:=","1*lambda/25","Z:=", "-lambda/5/2"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","striptel3:Scale:1"],["NAME:ChangedProps",["NAME:Scale of X","Value:=", "1"],["NAME:Scale of Y","Value:=", "1"],["NAME:Scale of Z","Value:=", "1"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","striptel3:Rotate:1"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","striptel3:Rotate:2"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","striptel3:CreateCylinder:1"],["NAME:ChangedProps",["NAME:Center Position","X:=","0","Y:=","1*lambda/25","Z:=", "-lambda/5/2"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","striptel4:Scale:1"],["NAME:ChangedProps",["NAME:Scale of X","Value:=", "1"],["NAME:Scale of Y","Value:=", "1"],["NAME:Scale of Z","Value:=", "1"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","striptel4:Rotate:1"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","striptel4:Rotate:2"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","striptel4:CreateCylinder:1"],["NAME:ChangedProps",["NAME:Center Position","X:=","0","Y:=","1*lambda/25","Z:=", "-lambda/5/2"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","striptel5:Scale:1"],["NAME:ChangedProps",["NAME:Scale of X","Value:=", "1"],["NAME:Scale of Y","Value:=", "1"],["NAME:Scale of Z","Value:=", "1"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","striptel5:Rotate:1"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","striptel5:Rotate:2"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","striptel5:CreateCylinder:1"],["NAME:ChangedProps",["NAME:Center Position","X:=","0","Y:=","1*lambda/25","Z:=", "-lambda/5/2"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","striptel6:Scale:1"],["NAME:ChangedProps",["NAME:Scale of X","Value:=", "1"],["NAME:Scale of Y","Value:=", "1"],["NAME:Scale of Z","Value:=", "1"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","striptel6:Rotate:1"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","striptel6:Rotate:2"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","striptel6:CreateCylinder:1"],["NAME:ChangedProps",["NAME:Center Position","X:=","0","Y:=","1*lambda/25","Z:=", "-lambda/5/2"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Moving_real:Scale:2"],["NAME:ChangedProps",["NAME:Scale of X","Value:=", "1"],["NAME:Scale of Y","Value:=", "1"],["NAME:Scale of Z","Value:=", "1"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Moving_real:Rotate:1"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Moving_real:Rotate:2"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Moving_imag:Scale:2"],["NAME:ChangedProps",["NAME:Scale of X","Value:=", "1"],["NAME:Scale of Y","Value:=", "1"],["NAME:Scale of Z","Value:=", "1"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Moving_imag:Rotate:1"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","Moving_imag:Rotate:2"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","EquationCurve7:Scale:1"],["NAME:ChangedProps",["NAME:Scale of X","Value:=", "1"],["NAME:Scale of Y","Value:=", "1"],["NAME:Scale of Z","Value:=", "1"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","EquationCurve7:Rotate:1"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","EquationCurve7:Rotate:2"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","EquationCurve7:CreateEquationCurve:1"],["NAME:ChangedProps",["NAME:Y(_t)","Value:=","1*lambda/25*sin(_t)"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","striptelmax:Scale:1"],["NAME:ChangedProps",["NAME:Scale of X","Value:=", "1"],["NAME:Scale of Y","Value:=", "1"],["NAME:Scale of Z","Value:=", "1"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","striptelmax:Rotate:1"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","striptelmax:Rotate:2"],["NAME:ChangedProps",["NAME:Angle",	"Value:="," 0deg"]]]])
oEditor.ChangeProperty(["NAME:AllTabs",["NAME:Geometry3DCmdTab",["NAME:PropServers","striptelmax:CreateCylinder:1"],["NAME:ChangedProps",["NAME:Center Position","X:=","0","Y:=","1*lambda/25","Z:=", "-lambda/5/2"]]]])
